### ISSUE TITLE
OOP-1-review-2022-10-15

### ISSUE THREAD

**Issue by hamerlinski** [krzysztof119/Object-programing#1]
**Task 1**
- [ ] Proper communication/interaction between classes and objects is missing.
- [x] Rename repository to **oop-put-course**
- [x] Add file extension

**Task 2**
- [x] Add file extension
- [x] Try to figure out better name for method than `getInfo`
